postgresql-8.1 has its binaries in /usr/lib/postgresql/8.1/bin. Added extra check.
git-svn-id: https://dev.snt.utwente.nl/svn/snt-syscom/snt-backup/trunk@37 53864893-6df6-0310-a35a-92b7ff90ca16

diff --git a/root/usr/lib/snt-backup/plugins/pgsql b/root/usr/lib/snt-backup/plugins/pgsql
--- a/root/usr/lib/snt-backup/plugins/pgsql
+++ b/root/usr/lib/snt-backup/plugins/pgsql
@@ -26,9 +26,15 @@ function pgsql_backup {
 
 	TOFILE="pgsql_${DATEFIX}.sql"
 
-	"${BASEDIR}/bin/rmt-client.pl" "${TODIR}/${TOFILE}${C_TAG}${E_TAG}" \
-		su postgres -c '/usr/lib/postgresql/bin/pg_dumpall -g' $COMPRESS $ENCRYPT \
-		|| { touch "${SNAPSHOTDIR}/error"; echo 'pgsql dump failed.'; }
+	if [ -x '/usr/lib/postgresql/bin/pg_dumpall' ]; then
+		"${BASEDIR}/bin/rmt-client.pl" "${TODIR}/${TOFILE}${C_TAG}${E_TAG}" \
+			su postgres -c '/usr/lib/postgresql/bin/pg_dumpall -g' $COMPRESS $ENCRYPT \
+			|| { touch "${SNAPSHOTDIR}/error"; echo 'pgsql dump failed.'; }
+	elif [ -x '/usr/lib/postgresql/8.1/bin/pg_dumpall' ]; then
+		"${BASEDIR}/bin/rmt-client.pl" "${TODIR}/${TOFILE}${C_TAG}${E_TAG}" \
+			su postgres -c '/usr/lib/postgresql/8.1/bin/pg_dumpall -g' $COMPRESS $ENCRYPT \
+			|| { touch "${SNAPSHOTDIR}/error"; echo 'pgsql dump failed.'; }
+	fi
 }
 
 #
